field: 16656e31-b433-43ce-8a88-36e79a55c6a3
fieldLayouts:
  5b52352c-3c2e-4e11-9382-935742711994:
    tabs:
      -
        elements:
          -
            fieldUid: 66239a45-46ae-4b4e-88a6-551c42f265e6
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c54ded95-29a6-497a-9939-f36dfb96885e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 807bb60c-1e56-42b5-b03d-74ca0eaa6d58
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d159cd45-691e-482c-b68e-86d0a8956d6d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  66239a45-46ae-4b4e-88a6-551c42f265e6:
    contentColumnType: text
    fieldGroup: null
    handle: header
    instructions: ''
    name: Header
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  807bb60c-1e56-42b5-b03d-74ca0eaa6d58:
    contentColumnType: text
    fieldGroup: null
    handle: bgColor
    instructions: ''
    name: 'Bg Color'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c54ded95-29a6-497a-9939-f36dfb96885e:
    contentColumnType: text
    fieldGroup: null
    handle: body
    instructions: ''
    name: Body
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d159cd45-691e-482c-b68e-86d0a8956d6d:
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: image
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:63965fd3-cca4-4261-a370-7a655386c58e'
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:63965fd3-cca4-4261-a370-7a655386c58e'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: faq
name: 'Frequently Asked Questions'
sortOrder: 4
