field: 16656e31-b433-43ce-8a88-36e79a55c6a3
fieldLayouts:
  ef28ba08-0c65-47a2-833f-c44e20973bca:
    tabs:
      -
        elements:
          -
            fieldUid: 5036dabd-f8f0-4238-9925-9729bd7ba18a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b673c34c-7409-4990-a0d9-ffcd1ef061dd
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9daed197-0853-4b53-843b-c7b48f78401b
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  5036dabd-f8f0-4238-9925-9729bd7ba18a:
    contentColumnType: text
    fieldGroup: null
    handle: header
    instructions: ''
    name: Header
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  9daed197-0853-4b53-843b-c7b48f78401b:
    contentColumnType: string
    fieldGroup: null
    handle: featuredGames
    instructions: ''
    name: 'Featured Games'
    searchable: false
    settings:
      allowSelfRelations: false
      limit: ''
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  b673c34c-7409-4990-a0d9-ffcd1ef061dd:
    contentColumnType: text
    fieldGroup: null
    handle: desc
    instructions: ''
    name: Description
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: featuredGames
name: 'Featured Games'
sortOrder: 1
