field: 16656e31-b433-43ce-8a88-36e79a55c6a3
fieldLayouts:
  636a5f56-5f89-4e57-b991-3bbc1aa6070a:
    tabs:
      -
        elements:
          -
            fieldUid: 56e11564-cefb-48d5-b9f6-ea913570e72f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a98e25b8-9791-4243-b15d-60d2af72eb84
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: de6a23c3-e33d-4505-9a08-721187fe8788
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6c272b84-6e58-4d22-b93e-ad6e96301abd
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  56e11564-cefb-48d5-b9f6-ea913570e72f:
    contentColumnType: text
    fieldGroup: null
    handle: header
    instructions: ''
    name: Header
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  6c272b84-6e58-4d22-b93e-ad6e96301abd:
    contentColumnType: string(255)
    fieldGroup: null
    handle: button
    instructions: ''
    name: Button
    searchable: false
    settings:
      maxLength: '255'
      placeholder: null
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  a98e25b8-9791-4243-b15d-60d2af72eb84:
    contentColumnType: text
    fieldGroup: null
    handle: body
    instructions: ''
    name: Body
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  de6a23c3-e33d-4505-9a08-721187fe8788:
    contentColumnType: text
    fieldGroup: null
    handle: bgColor
    instructions: ''
    name: 'Bg Color'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: paragraph
name: Paragraph
sortOrder: 1
