field: 16656e31-b433-43ce-8a88-36e79a55c6a3
fieldLayouts:
  b537196a-ac64-4479-a08f-4e9b9781947e:
    tabs:
      -
        elements:
          -
            fieldUid: 00e98488-9b7b-493b-86c4-9dddcc856afd
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f2e0e078-ba54-4c20-bd06-46665c94a637
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5a25de99-0da4-422f-8dee-8d94110f6492
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 959e3cd7-d6ca-49b9-9635-e8e7855f3df9
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  00e98488-9b7b-493b-86c4-9dddcc856afd:
    contentColumnType: text
    fieldGroup: null
    handle: header
    instructions: ''
    name: Header
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  5a25de99-0da4-422f-8dee-8d94110f6492:
    contentColumnType: integer(10)
    fieldGroup: null
    handle: numberOfPost
    instructions: ''
    name: 'Number Of Post'
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: '0'
      prefix: null
      previewCurrency: ''
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  959e3cd7-d6ca-49b9-9635-e8e7855f3df9:
    contentColumnType: text
    fieldGroup: null
    handle: bgColor
    instructions: ''
    name: 'Bg Color'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f2e0e078-ba54-4c20-bd06-46665c94a637:
    contentColumnType: text
    fieldGroup: null
    handle: desc
    instructions: ''
    name: Desc
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: recentPost
name: 'Recent Post'
sortOrder: 3
