fieldLayouts:
  04447365-13f5-4911-9e45-17b3fb4b17a8:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: engine
name: Engine
siteSettings:
  b36c8447-b853-4927-84df-8ff556c38632:
    hasUrls: true
    template: games\index
    uriFormat: 'games?engine={slug}'
structure:
  maxLevels: null
  uid: c7d9878e-71b6-41a1-86c7-4237be66d306
