enableVersioning: true
handle: games
name: Games
propagationMethod: all
siteSettings:
  b36c8447-b853-4927-84df-8ff556c38632:
    enabledByDefault: true
    hasUrls: true
    template: games\index
    uriFormat: 'games/{slug}'
type: channel
